version: '3.8'
services:
  db:
    image: postgres:16.2
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./backend-test:/var/lib/postgres/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - NODE_PORT=${NODE_PORT}
      - JWT_SECRET=${JWT_SECRET}
